[package]
name = "nekohub-tui"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[[bin]]
name = "nekohub"
path = "src/main.rs"

[dependencies]
async-trait.workspace = true
clap.workspace = true
crossterm.workspace = true
dirs.workspace = true
nekohub-core = { path = "../nekohub-core" }
nekohub-ssh = { path = "../nekohub-ssh" }
futures-util.workspace = true
ratatui.workspace = true
tokio.workspace = true

[lints]
workspace = true
