[package]
name = "nekohub-tui"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[[bin]]
name = "nekohub"
path = "src/main.rs"

[dependencies]
async-trait.workspace = true
clap.workspace = true
crossterm.workspace = true
dirs.workspace = true
nekohub-core = { path = "../nekohub-core" }
nekohub-agent = { path = "../nekohub-agent" }
futures-util.workspace = true
ratatui.workspace = true
tokio.workspace = true

[dev-dependencies]
tempfile = "3.27.0"

[lints]
workspace = true
